import {existsSync, readFileSync, unlinkSync, writeFileSync} from 'node:fs';
import amplifyAdapter from 'amplify-adapter';
import vercelAdapter from '@sveltejs/adapter-vercel';
import {detectPlatform} from './scripts/detectPlatform.js';

const AMPLIFY_OUTPUTS_PATH = './amplify_outputs.json';
const PLACEHOLDER_PATH = './scripts/amplifyOutputsPlaceholder.json';

const platform = detectPlatform();

function isPlaceholder(path) {
    try {
        return JSON.parse(readFileSync(path, 'utf-8'))._isPlaceholder === true;
    } catch {
        return false;
    }
}

// amplify_outputs.json is gitignored and only ever generated by an Amplify backend
// deploy (ampx sandbox / pipeline-deploy) — it won't exist on a fresh Vercel checkout.
// src/lib/server/auth/cognito/authService.ts and src/lib/client/amplifyClient.ts both
// statically import it, and Vite needs the file to physically exist at build time to
// resolve that import — even on the 'vercel' platform, where that code is
// bundled-but-never-invoked (see src/lib/server/storage/index.ts). A clearly marked
// placeholder satisfies the import without touching anything for a real AWS build.
if (platform === 'vercel') {
    if (!existsSync(AMPLIFY_OUTPUTS_PATH)) {
        writeFileSync(AMPLIFY_OUTPUTS_PATH, readFileSync(PLACEHOLDER_PATH, 'utf-8'));
    }
} else if (isPlaceholder(AMPLIFY_OUTPUTS_PATH)) {
    // A prior Vercel build left this behind — remove it so an AWS build correctly fails
    // loudly if the real file genuinely isn't present, instead of silently building with
    // fake Cognito/AppSync config.
    unlinkSync(AMPLIFY_OUTPUTS_PATH);
}

// Picked per-platform at build time — see scripts/detectPlatform.js. This is the
// build-time counterpart to the runtime repository/email/reviews-cache provider
// selection in src/lib/server/storage/index.ts and src/lib/server/email/index.ts.
const adapter = platform === 'vercel' ? vercelAdapter : amplifyAdapter;

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter()
	}
};

export default config;
